### ISSUE TITLE
api.php always inits the admin store. Module requires app store to not be admin.

### ISSUE THREAD

**Issue by tomasgriffin** [Vinai/VinaiKopp_Api2SessionAuthAdapter#4]
`\VinaiKopp_Api2SessionAuthAdapter_Model_Auth_Adapter_Session::isApplicableToRequest` line `89`

``` php
        if ($helper->getApp()->getStore()->isAdmin()) {
            return false;
        }
```

Always returns `false` due to `/api.php` line `55`:

``` php
Mage::init('admin');
```

As described in https://github.com/Vinai/VinaiKopp_Api2SessionLogin, my implementation (a SPA) is triggering a `POST` request to `/session/customer` endpoint however this throws an exception for the same reason when `\VinaiKopp_Api2SessionAuthAdapter_Helper_Frontend_Session::startFrontendSession` is called. Is this the intended usage?

**Comment by Vinai** [comment]
Before calling `startFrontendSession` the method `\VinaiKopp_Api2SessionAuthAdapter_Helper_Frontend_Session::initFrontendStore` needs to be called to set up the frontend context for the request.
Does that help?

**Comment by Vinai** [comment]
Hm, sorry, replied too early. I don't yet quite understand.

**Comment by Vinai** [comment]
Interesting, I am running the previous version of this code. The change happened in the commit https://github.com/Vinai/VinaiKopp_Api2SessionAuthAdapter/commit/7c354c1d641d54774be155c82474dda45d7b677c
@LeeSaferite - can you please chime in here? As @tomasgriffin write, the store context Magento sets up for requests to the `api.php` is always `admin`.
How do you handle that? Do you use a different entry point?

**Comment by tomasgriffin** [comment]
@Vinai `/api.php` has always set the store context as `admin` - all I can think is that a different entry point is being used as you say. You can fix this issue by passing a `?___store=1` param to the request but this isn't ideal.

**Comment by Vinai** [comment]
This was the previous version of the method: https://github.com/Vinai/VinaiKopp_Api2SessionAuthAdapter/blob/e666ec93f36355a6108ce178db6344c2a47322b7/app/code/community/VinaiKopp/Api2SessionAuthAdapter/Model/Auth/Adapter/Session.php#L84-L95

**Comment by tomasgriffin** [comment]
Seems the module now depends on the `store` cookie being set. Maybe it should check the current store context, if it's `admin`, use the `default` store instead?

**Comment by Vinai** [comment]
I want to wait for @LeeSaferite to maybe give share some light on how they are using it now, and then decide. If he doesn't reply in a week or two I'll go ahead and revert the behavior to the previous state.

**Comment by keyurshah070** [comment]
@Vinai How can I use this module? from browser URL or I need to create a script? I would be grateful If you can share light on this.

**Comment by Vinai** [comment]
This module needs to be consumed by other modules.

**Comment by keyurshah070** [comment]
Thank you for the response. Do you have the link of other module?  And any sample code hunt ?

**Comment by keyurshah070** [comment]
I also have the same problem, It always sets the admin store on 

`        if ($helper->getApp()->getStore()->isAdmin()) {
`

Any Idea on this ? @Vinai @tomasgriffin @LeeSaferite

**Comment by tomasgriffin** [comment]
@keyurshah070 Once a customer logs in to the frontend of Magento, a `store` cookie should be set with the ID of the current store. So long as this is sent along with the request to the /api/rest/* route, the `if ($helper->getApp()->getStore()->isAdmin()) {` statement should return false.

**Comment by keyurshah070** [comment]
@tomasgriffin thanks for the response. Yes, I debugged the code but frontend cookie is not set even though I log in to the site.  Any idea on this?
